debugged init.d script to work with systemd

diff --git a/etc/init.d/tessdb b/etc/init.d/tessdb
--- a/etc/init.d/tessdb
+++ b/etc/init.d/tessdb
@@ -38,6 +38,9 @@ CONFIG_FILE=/etc/$NAME/config
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
 
+# Override verbose value to work with systemd
+VERBOSE=yes
+
 # Define LSB log_* functions.
 # Depend on lsb-base (>= 3.2-14) to ensure that this file is present
 # and status_of_proc is working.
@@ -62,6 +65,7 @@ do_start()
 	# Add code here, if necessary, that waits for the process to be ready
 	# to handle requests from services started subsequently which depend
 	# on this one.  As a last resort, sleep for some time.
+	return 0
 }
 
 #
@@ -147,42 +151,42 @@ case "$1" in
 	# If do_reload() is not implemented then leave this commented out
 	# and leave 'force-reload' as an alias for 'restart'.
 	#
-	log_daemon_msg "Reloading $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Reloading $DESC" "$NAME"
 	do_reload
-	log_end_msg $?
+	[ "$VERBOSE" != no ] && log_end_msg $?
 	;;
     pause)
-	log_daemon_msg "Pausing $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Pausing $DESC" "$NAME"
 	do_pause
-	log_end_msg $?
+	[ "$VERBOSE" != no ] && log_end_msg $?
 	;;
     resume)
 	#
 	# If do_pause() is not implemented then leave this commented out
 	#
-	log_daemon_msg "Resume $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Resume $DESC" "$NAME"
 	do_resume
-	log_end_msg $?
+	[ "$VERBOSE" != no ] && log_end_msg $?
 	;;
     restart|force-reload)
 	#
 	# If the "reload" option is implemented then remove the
 	# 'force-reload' alias
 	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Restarting $DESC" "$NAME"
 	do_stop
 	case "$?" in
 	    0|1)
 		do_start
 		case "$?" in
-		    0) log_end_msg 0 ;;
-		    1) log_end_msg 1 ;; # Old process is still running
-		    *) log_end_msg 1 ;; # Failed to start
+		    0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		    1) [ "$VERBOSE" != no ] && log_end_msg 1 ;; # Old process is still running
+		    *) [ "$VERBOSE" != no ] && log_end_msg 1 ;; # Failed to start
 		esac
 		;;
 	    *)
 		# Failed to stop
-		log_end_msg 1
+		[ "$VERBOSE" != no ] && log_end_msg 1
 		;;
 	esac
 	;;
